autointegrated: true
currentnamespace: kubemq
currentstatefulset: kubemq
host: localhost
grpcport: 50000
restport: 9090
apiport: 8080
issecured: false
certfile: ""
kubeconfigpath: ""
connectiontype: grpc
defaulttoken: ""
clientid: command
authtokenfile: ""
licensedata: ""
licensekey: ""
